# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-09 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='content',
            field=models.TextField(default='this is the content', help_text='Article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detail',
            name='description',
            field=models.TextField(default='this is content', help_text='What is the article about?'),
            preserve_default=False,
        ),
    ]
