# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-09 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170109_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='content',
            field=models.TextField(help_text='Content'),
        ),
    ]
