# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-09 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170109_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='content',
        ),
    ]
