# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-09 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_detail_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='this is content', help_text='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default=1, help_text='What is the article about?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
